[package]
name = "ram-check-egui"
version = "1.0.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
egui = "0.32.3"

[dependencies.windows]
version = "0.62.1"
features = ["Win32_System_SystemInformation"]

[build-dependencies]
winres = "0.1.12"
